# this is a basic workflow to help you to get started with Actions

name: CI 

# Controls when the workflow will run

on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
   # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build : 
    runs-on : ubuntu-latest
    steps : 
    - uses : actions/checkout@v3
    - name : Run a one-line script
    - run : echo Hello, world!
    - name : Run a multi-line script
    run : |
           echo Add other actions to build,
           echo test, and deploy your project
   
